---
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: fleetpulse-backend
    volumes:
      - ${FLEETPULSE_DATA_PATH:-./data}:/data
    ports:
      - "8000:8000"  # Backend API
    restart: unless-stopped
    environment:
      - FLEETPULSE_DATA_DIR=/data
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-uvicorn}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-2}
      # OpenTelemetry configuration
      - OTEL_SERVICE_NAME=fleetpulse-backend
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_ENVIRONMENT=${OTEL_ENVIRONMENT:-development}
      - OTEL_ENABLE_TELEMETRY=${OTEL_ENABLE_TELEMETRY:-true}
      - OTEL_EXPORTER_TYPE=${OTEL_EXPORTER_TYPE:-jaeger}
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_TRACE_SAMPLE_RATE=${OTEL_TRACE_SAMPLE_RATE:-1.0}
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - fleetpulse
    depends_on:
      - jaeger

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fleetpulse-frontend
    ports:
      - "8080:80"  # Frontend UI
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - fleetpulse

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: fleetpulse-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Accept jaeger.thrift over HTTP
      - "6831:6831/udp"  # Accept jaeger.thrift over UDP (agents)
      - "6832:6832/udp"  # Accept jaeger.thrift over UDP (agents, compact)
      - "5778:5778"     # Serve configs (sampling strategies, etc.)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    restart: unless-stopped
    networks:
      - fleetpulse

networks:
  fleetpulse:
    driver: bridge
