---
services:
  fleetpulse:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: fleetpulse-app-test
    ports:
      - "8080:8000"
    volumes:
      - /tmp/dockervolumes/fleetpulse:/data
    environment:
      - NODE_ENV=production
      - FLEETPULSE_DATA_PATH=""
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s