---
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: fleetpulse-backend
    volumes:
      - ${FLEETPULSE_DATA_PATH:-./data}:/data
    ports:
      - "8000:8000"  # Backend API
    restart: unless-stopped
    environment:
      - FLEETPULSE_DATA_DIR=/data
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-uvicorn}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-2}
    networks:
      - fleetpulse

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fleetpulse-frontend
    ports:
      - "8080:80"  # Frontend UI
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - fleetpulse

networks:
  fleetpulse:
    driver: bridge
