---
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fleet-backend
    volumes:
      - /mnt/data/dockervolumes/fleetpulse:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fleet-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
