---
services:
  fleetpulse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleetpulse-combined
    volumes:
      - ${FLEETPULSE_DATA_PATH:-./data}:/data
    ports:
      - "8080:8000"
    restart: unless-stopped
