# OpenTelemetry Collector configuration for FleetPulse
# This configuration receives OTLP traces and metrics from the backend
# and forwards them to Jaeger for visualization

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  resource:
    attributes:
      - key: service.instance.id
        from_attribute: host.name
        action: upsert

exporters:
  # Export traces to Jaeger
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Export metrics (optional - for debugging)
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

  # Prometheus metrics endpoint (optional)
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [jaeger]
    
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging, prometheus]
  
  extensions: []
  
  telemetry:
    logs:
      level: "info"
    metrics:
      level: "basic"
      address: 0.0.0.0:8888